============================= test session starts ==============================
platform linux -- Python 3.12.8, pytest-8.3.4, pluggy-1.5.0
rootdir: /home/runner/work/Assessment-Backend-Week-1/Assessment-Backend-Week-1
collected 112 items

days_api/test_api.py ................................................FFF [ 45%]
FFF.FFFF.F.FFFFFFFFFFF                                                   [ 65%]
days_api/test_date_functions.py .......................................  [100%]

======================== 22 failed, 90 passed in 0.35s =========================
************* Module app
days_api/app.py:45:4: W0702: No exception type(s) specified (bare-except)
days_api/app.py:58:4: W0621: Redefining name 'date' from outer scope (line 5) (redefined-outer-name)
days_api/app.py:66:4: W0621: Redefining name 'weekday' from outer scope (line 54) (redefined-outer-name)
days_api/app.py:64:4: W0702: No exception type(s) specified (bare-except)
days_api/app.py:87:8: W0621: Redefining name 'app_history' from outer scope (line 12) (redefined-outer-name)
days_api/app.py:75:4: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
days_api/app.py:84:28: E0601: Using variable 'app_history' before assignment (used-before-assignment)
days_api/app.py:5:0: W0611: Unused date imported from datetime (unused-import)
days_api/app.py:7:0: W0611: Unused Response imported from flask (unused-import)
days_api/app.py:9:0: W0611: Unused get_current_age imported from date_functions (unused-import)
************* Module date_functions
days_api/date_functions.py:11:8: W0707: Consider explicitly re-raising using 'except ValueError as exc' and 'raise ValueError('Unable to convert value to datetime.') from exc' (raise-missing-from)

-----------------------------------
Your code has been rated at 8.10/10

